# Generated by Django 3.1.1 on 2020-11-06 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperEasyapp', '0006_auto_20201016_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 13, 46, 24, 913773)),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 6, 13, 46, 24, 911778)),
        ),
    ]
